### PR TITLE
[OP] Add oneDNN Slice test.

### PR DESCRIPTION
**Pull request by jmaksymc**
Here are the results for Slice test:
sliceres

### CODE REVIEW

**Comment by marvin-Yu** [comment]
I can not pass the `bazel test`, could help to double check the code. the test command shows as follow and the error infos also attached.
``` shell
$ default_opt="--cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 \
--copt=-O3 --copt=-Wformat --copt=-Wformat-security \
--copt=-fstack-protector --copt=-fPIC \
--copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro \
--linkopt=-znow --linkopt=-fstack-protector \
--copt=-Wno-sign-compare \
--test_size_filters=small,medium,large,enormous \
--keep_going"

$ intel_opt="--config=mkl_threadpool \
--define build_with_mkl_dnn_v1_only=true \
--copt=-DENABLE_INTEL_MKL_BFLOAT16 \
--copt=-march=skylake-avx512"

$ UT_opt="--test_output=all --nocache_test_results"

# your UT target, such as
$ test_name="//tensorflow/core/kernels:mkl_slice_op_test"

$ bazel test $UT_opt $default_opt $intel_opt $test_name
```
image

**Comment by jmaksymc** [comment]
I'll check and fix this issue.

**Comment by app-on-mic** [comment]
It can't build successfully. Could you help to double check on that, please? Below is the issue.

image

**Comment by jmaksymc** [comment]
It is strange, your error shows that the line 135 of the code you are compiling is:
static std::string getTestCaseName(::testing::TestParamInfo<**SoftmaxTestParams**> obj) {
While in my code and in the commit there is:
static std::string getTestCaseName(::testing::TestParamInfo<**SliceTestParams**> obj) {
And this works totally fine on the machine I work on.
Please check if the code you were trying to compile is the same as in this PR.

**Pull request merged**
