### PR TITLE
[OP] add oneDNN transpose unit tests.

### PR DESCRIPTION
**Pull request by jmaksymc**
I checked it on a bf16 machine and it seems like transpose on bfloat16 fails at 3D and 4D tensors (works fine for 2D) and it might be caused because of the primitive, what should I do with it?

### CODE REVIEW

**Comment by jmaksymc** [comment]
So the issue with bf16 was caused because of the normal distribution of bf16, now it is set to set numbers between -100 and 100 and all the tests passed, here are the results:
image
image
image

**Comment by marvin-Yu** [comment]
image
Hi @jmaksymc could pls clean these commits, which is useless in our test PR.
same issue at #1 #3 #5 #13 #15 .

**Comment by marvin-Yu** [comment]
+1, It looks great to me, @changqi1  could you help to review this?

**Comment by changqi1** [comment]
@marvin-Yu  @jmaksymc  Merged.

**Pull request merged**
