### PR TITLE
[Modelzoo] Creat MMOE model

### PR DESCRIPTION
**Pull request by kmagiers**

### CODE REVIEW

**Comment by changqi1** [comment]
@kmagiers  give your AUC and perf data

**Comment by Duyi-Wang** [comment]
@kmagiers 
1. Please add model perf data in README, with reference to commit 9387a3406b3097990533f765caa835922b01a15f
2. Please rebase your commit

**Comment by Duyi-Wang** [comment]
1. Please use a 'head' scope to pack self.compute_loss(), acc & auc, it looks neater in tensorboard's graph, thx.
2. Please update community tensorflow version from 1.15 to 1.15.5 in DockerFile.
3. Line 224: please remove `.keep_weights()`

**Comment by Duyi-Wang** [comment]
You will get a error in line 238 `AttributeError: 'VariableScope' object has no attribute 'keep_weights'`
Because in code `with tf.variable_scope() as expert_layer_scope: `, firstly run `class variable_scope.__init__()` and then `variable_scope.__enter__()` to get a object of `VariableScope` assigned to `expert_layer_scope. keep_weights()` is member func of `class variable_scope` not `class VariableScope`.

**Comment by Duyi-Wang** [comment]
@kmagiers 
- acc calculation in line 204 need update.`self.acc, self.acc_op = tf.metrics.accuracy(labels=self.label, predictions=self.model)`
'tf.metrics.accuracy'  don't accept probability as predictions. 
Please update to `self.acc, self.acc_op = tf.metrics.accuracy(labels=self.label, predictions=tf.round(self.model))`
- Please rebase your commits.

**Comment by kmagiers** [comment]
> @kmagiers
> 
> 1. Please add model perf data in README, with reference to commit [9387a34](https://github.com/changqi1/DeepRec/commit/9387a3406b3097990533f765caa835922b01a15f)
> 2. Please rebase your commit

Done



> 1. Please use a 'head' scope to pack self.compute_loss(), acc & auc, it looks neater in tensorboard's graph, thx.
> 2. Please update community tensorflow version from 1.15 to 1.15.5 in DockerFile.
> 3. Line 224: please remove `.keep_weights()`

Done

> You will get an error in line 238, `AttributeError: 'VariableScope' object has no attribute 'keep_weights'`. Because in code `with tf.variable_scope() as expert_layer_scope: `, firstly run `class variable_scope.__init__()` and then `variable_scope.__enter__()` to get a object of `VariableScope` assigned to `expert_layer_scope`. `keep_weights()` is member func of `class variable_scope` not `class VariableScope`.

Done

> @kmagiers
> 
> * acc calculation in line 204 need update.`self.acc, self.acc_op = tf.metrics.accuracy(labels=self.label, predictions=self.model)`
>   'tf.metrics.accuracy'  don't accept probability as predictions.
>   Please update to `self.acc, self.acc_op = tf.metrics.accuracy(labels=self.label, predictions=tf.round(self.model))`
> * Please rebase your commits.

Done

**Comment by kmagiers** [comment]
@Duyi-Wang 
Please review code in proper manner: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request
putting comments and suggestions straight to the line in question will make it much easier to review and also then you can mark separate comments as Done which makes tracking easier

**Comment by changqi1** [comment]
Test AUC, ACC, Gsteps/sec on CPX

|  | ACC | |
| -- | -- | -- |
|   | value | percent |
| Community TF | 0.973787 | baseline |
| DeepRec FP32 | 0.973787 | 100.00% |
| DeepRec BF16 | 0.973787 | 100.00% |

|  | AUC | |
| -- | -- | --  |
|   | value | percent  |
| Community TF | 0.7432368 | baseline |
| DeepRec FP32 | 0.7444535 | 100.16% |
| DeepRec BF16 | 0.7453669 | 100.29% |

|  | Gsteps/s | |
| -- | -- | -- |
|   | value | percent |
| Community TF | 73.74488 | baseline |
| DeepRec FP32 | 93.01421 | 126.13% |
| DeepRec BF16 | 105.70906 | 143.34% |

**Pull request merged**
